services:
  database:
    image: postgres:18
    container_name: userManagementDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin