services:
  database:
    image: postgres:18
    container_name: userManagementDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  app:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/usermanagement
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin